#!/usr/bin/env python3
"""Read-only existence checks for the Glyph firmware workstream roadmap index."""

from __future__ import annotations

from pathlib import Path
import sys


REQUIRED_FILES = [
    "docs/calibration/glyph_firmware_workstream_roadmap_2026-05-26.md",
    "docs/calibration/glyph_firmware_workstream_roadmap_handoff.md",
    "docs/calibration/glyph_ultimate_tilt_runtime_implementation_2026-05-24.md",
    "docs/calibration/glyph_ultimate_tilt_hardware_test_result.md",
    "docs/calibration/glyph_ultimate_tilt_prehardware_readiness_index_2026-05-24.md",
    "docs/calibration/glyph_ultimate_preservation_hardware_matrix_2026-05-26.md",
    "docs/calibration/glyph_ultimate_preservation_hardware_result_TEMPLATE.md",
    "docs/calibration/glyph_full_capability_inventory_2026-05-26.md",
    "docs/calibration/glyph_remaining_functionality_gap_map_2026-05-26.md",
    "docs/calibration/glyph_profile_config_source_authority_2026-05-26.md",
    "docs/calibration/glyph_profile_config_semantics_gap_map_2026-05-26.md",
    "docs/calibration/glyph_profile_config_export_corpus_protocol_2026-05-26.md",
    "docs/calibration/glyph_profile_config_export_corpus_manifest_TEMPLATE.json",
    "docs/calibration/glyph_profile_config_adapter_policy_decisions_2026-05-26.md",
    "docs/calibration/glyph_profile_adapter_prewrite_validation_2026-05-26.md",
    "docs/calibration/glyph_physical_logical_layout_map_2026-05-26.md",
    "docs/calibration/glyph_native_ultimate_table_runtime_design_2026-05-26.md",
    "docs/calibration/glyph_native_ultimate_table_fixture_contract_2026-05-26.md",
    "docs/calibration/fixtures/glyph_native_ultimate_table_contract_TEMPLATE.json",
    "docs/calibration/glyph_native_ultimate_table_source_checker_2026-05-26.md",
    "docs/calibration/glyph_full_layout_requirements_spec_2026-05-26.md",
    "docs/calibration/glyph_full_layout_requirements_questions_2026-05-26.md",
    "docs/calibration/glyph_next_runtime_change_readiness_index_2026-05-26.md",
    "docs/calibration/glyph_full_firmware_workstream_sequence_handoff_2026-05-26.md",
    "docs/calibration/glyph_merged_state_consistency_audit_2026-05-26.md",
    "docs/calibration/glyph_controller_output_contract_v0_2026-05-27.md",
    "docs/calibration/glyph_native_ultimate_runtime_implementation_plan_v0_2026-05-27.md",
    "docs/calibration/glyph_user_requirements_input_packet_2026-05-27.md",
    "docs/calibration/glyph_preimplementation_blocker_index_2026-05-27.md",
    "docs/calibration/glyph_user_requirements_packet_checker_2026-05-27.md",
    "docs/calibration/glyph_preservation_hardware_execution_packet_2026-05-27.md",
    "docs/calibration/glyph_prehardware_rc_runbook_2026-05-27.md",
    "docs/calibration/glyph_prehardware_rc_runbook_checker_2026-05-27.md",
    "docs/calibration/glyph_prehardware_dry_run_checker_2026-05-27.md",
    "docs/calibration/glyph_no_forbidden_artifacts_checker_2026-05-27.md",
    "docs/calibration/glyph_manual_hardware_owner_checklist_2026-05-27.md",
    "docs/calibration/glyph_ultimate_tilt3_runtime_implementation_2026-05-27.md",
    "docs/calibration/glyph_ultimate_tilt3_hardware_test_plan_2026-05-27.md",
    "docs/calibration/glyph_smash_box_profile_output_tables_2026-05-27.md",
    "docs/calibration/glyph_smashbox_modifiers_runtime_implementation_2026-05-27.md",
    "docs/calibration/glyph_smashbox_modifiers_hardware_test_plan_2026-05-27.md",
    "docs/calibration/glyph_identity_runtime_smashbox_hardware_result_2026-05-28.md",
    "docs/calibration/glyph_identity_runtime_smashbox_latest_hardware_result_2026-05-28.md",
    "docs/calibration/glyph_identity_runtime_generated_config_prototype_2026-05-28.md",
    "docs/calibration/fixtures/glyph_identity_runtime_generated_config_prototype_2026-05-28.json",
    "docs/calibration/glyph_identity_runtime_generated_config_contract_v0_2026-05-28.md",
    "docs/calibration/fixtures/glyph_identity_runtime_generated_config_contract_v0_2026-05-28.json",
    "docs/calibration/glyph_senscope_to_glyph_export_contract_draft_2026-05-28.md",
    "docs/calibration/fixtures/glyph_senscope_to_glyph_export_contract_draft_2026-05-28.json",
    "docs/calibration/glyph_runtime_loaded_config_design_v0_2026-05-28.md",
    "docs/calibration/fixtures/glyph_runtime_loaded_config_design_v0_2026-05-28.json",
    "docs/calibration/glyph_runtime_loaded_config_validation_contract_v0_2026-05-28.md",
    "docs/calibration/fixtures/glyph_runtime_loaded_config_validation_contract_v0_2026-05-28.json",
    "docs/calibration/glyph_agentic_sequence_protocol_2026-06-03.md",
    "docs/calibration/fixtures/glyph_agentic_sequence_protocol_2026-06-03.json",
    "docs/calibration/glyph_offline_generated_config_validator_v0_2026-06-03.md",
    "docs/calibration/fixtures/glyph_offline_generated_config_validator_contract_v0_2026-06-03.json",
    "docs/calibration/glyph_generated_config_invalid_corpus_2026-06-03.md",
    "docs/calibration/fixtures/glyph_generated_config_invalid_corpus_2026-06-03.json",
    "docs/calibration/glyph_senscope_export_package_validator_draft_2026-06-03.md",
    "docs/calibration/fixtures/glyph_senscope_export_package_SAMPLE_2026-06-03.json",
    "docs/calibration/fixtures/glyph_senscope_export_package_invalid_corpus_2026-06-03.json",
    "docs/calibration/glyph_runtime_config_candidate_validator_v0_2026-06-03.md",
    "docs/calibration/fixtures/glyph_runtime_config_candidate_validator_contract_v0_2026-06-03.json",
    "docs/calibration/fixtures/glyph_runtime_config_candidate_SAMPLE_2026-06-03.json",
    "docs/calibration/glyph_runtime_config_candidate_invalid_corpus_2026-06-03.md",
    "docs/calibration/fixtures/glyph_runtime_config_candidate_invalid_corpus_2026-06-03.json",
    "docs/calibration/glyph_runtime_config_validation_report_2026-06-03.md",
    "docs/calibration/fixtures/glyph_runtime_config_validation_report_2026-06-03.json",
    "docs/calibration/glyph_export_artifact_compatibility_index_2026-06-03.md",
    "docs/calibration/fixtures/glyph_export_artifact_compatibility_index_2026-06-03.json",
    "docs/calibration/glyph_export_artifact_round_trip_2026-06-03.md",
    "docs/calibration/fixtures/glyph_export_artifact_round_trip_expectations_2026-06-03.json",
    "docs/calibration/glyph_export_artifact_canonical_snapshots_2026-06-03.md",
    "docs/calibration/fixtures/glyph_export_artifact_snapshots_2026-06-03.json",
    "docs/calibration/glyph_export_artifact_compatibility_invalid_corpus_2026-06-03.md",
    "docs/calibration/fixtures/glyph_export_artifact_compatibility_invalid_corpus_2026-06-03.json",
    "docs/calibration/glyph_configurator_compatibility_source_registry_2026-06-03.md",
    "docs/calibration/fixtures/glyph_configurator_compatibility_source_registry_2026-06-03.json",
    "docs/calibration/glyph_config_json_compatibility_fixtures_2026-06-03.md",
    "docs/calibration/fixtures/glyph_config_json_compatibility_cases_2026-06-03.json",
    "docs/calibration/glyph_import_export_compatibility_validator_2026-06-03.md",
    "docs/calibration/fixtures/glyph_import_export_compatibility_expectations_2026-06-03.json",
    "docs/calibration/glyph_external_remapper_adapter_boundary_2026-06-03.md",
    "docs/calibration/fixtures/glyph_external_remapper_adapter_boundary_2026-06-03.json",
    "docs/calibration/glyph_external_remapper_source_snapshot_index_2026-06-03.md",
    "docs/calibration/fixtures/glyph_external_remapper_source_snapshot_index_2026-06-03.json",
    "docs/calibration/glyph_external_remapper_config_shape_matrix_2026-06-03.md",
    "docs/calibration/fixtures/glyph_external_remapper_config_shape_matrix_2026-06-03.json",
    "docs/calibration/glyph_external_remapper_adapter_feasibility_2026-06-03.md",
    "docs/calibration/fixtures/glyph_external_remapper_adapter_feasibility_2026-06-03.json",
    "tools/check_glyph_external_remapper_adapter_feasibility.py",
    "docs/calibration/glyph_external_remapper_compatibility_experiment_plan_2026-06-03.md",
    "docs/calibration/fixtures/glyph_external_remapper_compatibility_experiment_plan_2026-06-03.json",
    "tools/check_glyph_external_remapper_compatibility_experiment_plan.py",
    "docs/calibration/glyph_offline_remapper_adapter_target_contract_2026-06-03.md",
    "docs/calibration/fixtures/glyph_offline_remapper_adapter_target_contract_2026-06-03.json",
    "tools/check_glyph_offline_remapper_adapter_target_contract.py",
    "docs/calibration/glyph_offline_remapper_adapter_mapping_plan_2026-06-03.md",
    "docs/calibration/fixtures/glyph_offline_remapper_adapter_mapping_plan_2026-06-03.json",
    "tools/check_glyph_offline_remapper_adapter_mapping_plan.py",
    "docs/calibration/glyph_offline_remapper_adapter_gap_matrix_2026-06-03.md",
    "docs/calibration/fixtures/glyph_offline_remapper_adapter_gap_matrix_2026-06-03.json",
    "tools/check_glyph_offline_remapper_adapter_gap_matrix.py",
    "docs/calibration/glyph_offline_remapper_manual_experiment_packet_2026-06-03.md",
    "docs/calibration/fixtures/glyph_offline_remapper_manual_experiment_packet_2026-06-03.json",
    "tools/check_glyph_offline_remapper_manual_experiment_packet.py",
    "docs/calibration/glyph_offline_remapper_experiment_input_manifest_2026-06-03.md",
    "docs/calibration/fixtures/glyph_offline_remapper_experiment_input_manifest_2026-06-03.json",
    "tools/check_glyph_offline_remapper_experiment_input_manifest.py",
    "docs/calibration/glyph_offline_remapper_manual_procedure_2026-06-03.md",
    "docs/calibration/fixtures/glyph_offline_remapper_manual_procedure_2026-06-03.json",
    "tools/check_glyph_offline_remapper_manual_procedure.py",
    "docs/calibration/glyph_offline_remapper_result_template_2026-06-03.md",
    "docs/calibration/fixtures/glyph_offline_remapper_result_TEMPLATE_2026-06-03.json",
    "tools/check_glyph_offline_remapper_result_template.py",
    "docs/calibration/glyph_offline_remapper_experiment_readiness_index_2026-06-03.md",
    "docs/calibration/fixtures/glyph_offline_remapper_experiment_readiness_index_2026-06-03.json",
    "tools/check_glyph_offline_remapper_experiment_readiness_index.py",
    "docs/calibration/glyph_offline_remapper_experiment_result_2026-06-04.md",
    "docs/calibration/fixtures/glyph_offline_remapper_experiment_result_2026-06-04.json",
    "docs/calibration/fixtures/glyph_offline_remapper_exported_GlyphUserProfiles_2026-06-04.json",
    "tools/check_glyph_offline_remapper_experiment_result.py",
    "docs/calibration/glyph_offline_remapper_export_structural_diff_2026-06-04.md",
    "docs/calibration/fixtures/glyph_offline_remapper_export_structural_diff_2026-06-04.json",
    "tools/analyze_glyph_offline_remapper_export_diff.py",
    "tools/check_glyph_offline_remapper_export_structural_diff.py",
    "docs/calibration/glyph_offline_remapper_ultimate_diff_report_2026-06-04.md",
    "docs/calibration/fixtures/glyph_offline_remapper_ultimate_diff_report_2026-06-04.json",
    "tools/check_glyph_offline_remapper_ultimate_diff_report.py",
    "docs/calibration/glyph_offline_remapper_metadata_diff_report_2026-06-04.md",
    "docs/calibration/fixtures/glyph_offline_remapper_metadata_diff_report_2026-06-04.json",
    "tools/check_glyph_offline_remapper_metadata_diff_report.py",
    "docs/calibration/glyph_offline_remapper_export_diff_gate_2026-06-04.md",
    "docs/calibration/fixtures/glyph_offline_remapper_export_diff_gate_2026-06-04.json",
    "tools/check_glyph_offline_remapper_export_diff_gate.py",
    "docs/calibration/glyph_offline_remapper_binding_loss_classification_2026-06-04.md",
    "docs/calibration/fixtures/glyph_offline_remapper_binding_loss_classification_2026-06-04.json",
    "tools/check_glyph_offline_remapper_binding_loss_classification.py",
    "docs/calibration/glyph_offline_remapper_socd_drift_classification_2026-06-04.md",
    "docs/calibration/fixtures/glyph_offline_remapper_socd_drift_classification_2026-06-04.json",
    "tools/check_glyph_offline_remapper_socd_drift_classification.py",
    "docs/calibration/glyph_offline_remapper_adapter_blocker_escalation_2026-06-04.md",
    "docs/calibration/fixtures/glyph_offline_remapper_adapter_blocker_escalation_2026-06-04.json",
    "tools/check_glyph_offline_remapper_adapter_blocker_escalation.py",
    "docs/calibration/glyph_offline_remapper_export_loss_gate_2026-06-04.md",
    "docs/calibration/fixtures/glyph_offline_remapper_export_loss_gate_2026-06-04.json",
    "tools/check_glyph_offline_remapper_export_loss_gate.py",
    "docs/calibration/glyph_clean_room_adapter_candidate_schema_contract_2026-06-04.md",
    "docs/calibration/fixtures/glyph_clean_room_adapter_candidate_schema_contract_2026-06-04.json",
    "tools/check_glyph_clean_room_adapter_candidate_schema_contract.py",
    "docs/calibration/glyph_clean_room_adapter_candidate_schema_validator_2026-06-04.md",
    "docs/calibration/fixtures/glyph_clean_room_adapter_candidate_SCHEMA_PLACEHOLDER_2026-06-04.json",
    "tools/check_glyph_clean_room_adapter_candidate_schema_validator.py",
    "docs/calibration/glyph_storage_transport_source_authority_registry_2026-06-03.md",
    "docs/calibration/fixtures/glyph_storage_transport_source_authority_registry_2026-06-03.json",
    "tools/check_glyph_storage_transport_source_authority_registry.py",
    "docs/calibration/glyph_protobuf_config_schema_research_packet_2026-06-03.md",
    "docs/calibration/fixtures/glyph_protobuf_config_schema_research_packet_2026-06-03.json",
    "tools/check_glyph_protobuf_config_schema_research_packet.py",
    "docs/calibration/glyph_webserial_transport_blocker_packet_2026-06-03.md",
    "docs/calibration/fixtures/glyph_webserial_transport_blocker_packet_2026-06-03.json",
    "tools/check_glyph_webserial_transport_blocker_packet.py",
    "docs/calibration/glyph_runtime_storage_interpreter_blocker_packet_2026-06-03.md",
    "docs/calibration/fixtures/glyph_runtime_storage_interpreter_blocker_packet_2026-06-03.json",
    "tools/check_glyph_runtime_storage_interpreter_blocker_packet.py",
    "docs/calibration/glyph_storage_transport_research_index_2026-06-03.md",
    "docs/calibration/fixtures/glyph_storage_transport_research_index_2026-06-03.json",
    "tools/check_glyph_storage_transport_research_index.py",
    "docs/calibration/glyph_preimplementation_go_nogo_index_2026-05-28.md",
    "docs/calibration/fixtures/glyph_preimplementation_go_nogo_index_2026-05-28.json",
    "docs/calibration/glyph_generated_constants_refactor_readiness_packet_2026-05-28.md",
    "docs/calibration/fixtures/glyph_generated_constants_refactor_readiness_packet_2026-05-28.json",
    "docs/calibration/glyph_runtime_loaded_config_implementation_readiness_packet_2026-05-28.md",
    "docs/calibration/fixtures/glyph_runtime_loaded_config_implementation_readiness_packet_2026-05-28.json",
    "docs/calibration/glyph_generated_constants_refactor_implementation_plan_v0_2026-05-28.md",
    "docs/calibration/fixtures/glyph_generated_constants_refactor_implementation_plan_v0_2026-05-28.json",
    "docs/calibration/glyph_generated_constants_refactor_execution_packet_2026-05-28.md",
    "docs/calibration/fixtures/glyph_generated_constants_refactor_execution_packet_2026-05-28.json",
    "docs/calibration/glyph_generated_constants_refactor_agent_prompt_2026-05-28.md",
    "docs/calibration/glyph_generated_constants_refactor_hardware_test_matrix_2026-05-28.md",
    "docs/calibration/fixtures/glyph_generated_constants_refactor_hardware_test_matrix_2026-05-28.json",
    "docs/calibration/glyph_generated_constants_refactor_hardware_result_2026-06-03.md",
    "docs/calibration/fixtures/glyph_generated_constants_refactor_hardware_result_2026-06-03.json",
    "docs/calibration/glyph_runtime_loaded_config_implementation_plan_v0_2026-05-28.md",
    "docs/calibration/fixtures/glyph_runtime_loaded_config_implementation_plan_v0_2026-05-28.json",
    "docs/calibration/glyph_identity_runtime_hardware_validation_and_rollback_plan_2026-05-28.md",
    "docs/calibration/fixtures/glyph_identity_runtime_hardware_validation_and_rollback_plan_2026-05-28.json",
    "docs/calibration/glyph_ultimate_lt3_profile_binding_2026-05-27.md",
    "docs/calibration/glyph_active_ultimate_lt3_config_artifact_2026-05-27.md",
    "docs/calibration/glyph_ultimate_identity_profile_baseline_2026-05-27.md",
    "docs/calibration/glyph_ultimate_lt3_standalone_hardware_result_2026-05-27.md",
    "docs/calibration/glyph_ultimate_lt3_dpad_fix_hardware_result_2026-05-27.md",
    "docs/calibration/glyph_serial_active_config_writer_trace_2026-05-27.md",
    "docs/calibration/glyph_senscope_workflow_and_config_migration_plan_2026-05-27.md",
    "docs/calibration/artifacts/glyph_ultimate_mvp_lt3_active_config_PROFILE.json",
    "tools/run_glyph_ultimate_tilt_prehardware_checks.py",
    "tools/check_glyph_ultimate_tilt_hardware_result.py",
    "tools/check_glyph_ultimate_tilt_rc_manifest.py",
    "tools/check_glyph_profile_config_semantics.py",
    "tools/check_glyph_profile_config_export_corpus.py",
    "tools/check_glyph_profile_adapter_prewrite.py",
    "tools/list_glyph_physical_logical_layout_sources.py",
    "tools/check_glyph_ultimate_preservation_hardware_result.py",
    "tools/check_glyph_native_ultimate_table_fixture.py",
    "tools/check_glyph_native_ultimate_table_runtime_scope.py",
    "tools/run_glyph_next_runtime_change_readiness_checks.py",
    "tools/check_glyph_merged_state_consistency.py",
    "tools/check_glyph_preimplementation_blockers.py",
    "tools/check_glyph_user_requirements_packet.py",
    "tools/check_glyph_preservation_execution_packet.py",
    "tools/check_glyph_agentic_sequence_protocol.py",
    "tools/check_glyph_prehardware_rc_runbook.py",
    "tools/inspect_glyph_mk6_build_artifact.py",
    "tools/run_glyph_prehardware_dry_run_checks.py",
    "tools/check_glyph_no_forbidden_artifacts.py",
    "tools/check_glyph_manual_hardware_owner_checklist.py",
    "tools/check_glyph_ultimate_tilt3_runtime_source.py",
    "tools/check_glyph_smashbox_profile_tables.py",
    "tools/check_glyph_smashbox_modifiers_runtime_source.py",
    "tools/check_glyph_smashbox_identity_runtime_bindings.py",
    "tools/generate_glyph_identity_runtime_config_prototype.py",
    "tools/check_glyph_identity_runtime_generated_config_prototype.py",
    "tools/check_glyph_identity_runtime_config_contracts.py",
    "tools/glyph_generated_config_validator.py",
    "tools/check_glyph_generated_config_validator.py",
    "tools/check_glyph_generated_config_invalid_corpus.py",
    "tools/check_glyph_senscope_export_package_validator.py",
    "tools/glyph_runtime_config_candidate_validator.py",
    "tools/check_glyph_runtime_config_candidate_validator.py",
    "tools/check_glyph_runtime_config_candidate_invalid_corpus.py",
    "tools/generate_glyph_runtime_config_validation_report.py",
    "tools/check_glyph_runtime_config_validation_report.py",
    "tools/check_glyph_export_artifact_compatibility_index.py",
    "tools/check_glyph_export_artifact_round_trip.py",
    "tools/generate_glyph_export_artifact_snapshots.py",
    "tools/check_glyph_export_artifact_snapshots.py",
    "tools/check_glyph_export_artifact_compatibility_invalid_corpus.py",
    "tools/check_glyph_configurator_compatibility_source_registry.py",
    "tools/check_glyph_config_json_compatibility_fixtures.py",
    "tools/check_glyph_import_export_compatibility.py",
    "tools/check_glyph_external_remapper_adapter_boundary.py",
    "tools/check_glyph_external_remapper_source_snapshot_index.py",
    "tools/check_glyph_external_remapper_config_shape_matrix.py",
    "tools/check_glyph_runtime_loaded_config_design.py",
    "tools/check_glyph_preimplementation_go_nogo_index.py",
    "tools/check_glyph_implementation_planning_packets.py",
    "tools/check_glyph_generated_constants_refactor_execution_packet.py",
    "tools/check_glyph_generated_constants_refactor_hardware_result.py",
    "tools/check_glyph_ultimate_lt3_profile_binding.py",
    "tools/check_glyph_active_ultimate_lt3_config_artifact.py",
    "tools/check_glyph_ultimate_identity_profile_baseline.py",
    "tools/check_glyph_ultimate_dpad_profile_mapping.py",
    "tools/check_glyph_serial_config_writer.py",
    "tools/check_glyph_senscope_workflow_plan.py",
    "tools/glyph_serial_config_tool.py",
]

OPTIONAL_FUTURE_FILES = [
    "docs/calibration/glyph_ultimate_preservation_hardware_result.md",
    "docs/calibration/export_corpus",
]

REQUIRED_ROADMAP_PHRASES = [
    "WebSerial transport blocker packet",
    "glyph/gfw2-webserial-transport-blocker-packet",
    "serial dry-run is not live device access",
    "WebSerial write, device write, and firmware flashing are not implemented",
    "external WebSerial observations are non-authoritative",
    "Runtime storage/interpreter blocker packet",
    "glyph/gfw2-runtime-storage-interpreter-blocker-packet",
    "runtime-loaded config, storage, and interpreter are not implemented",
    "firmware owns evaluator phase order and allowed role classes",
    "config must not own scripts/macros/turbo/timing/history or phase-order mutation",
    "the packet is not hardware validation",
    "storage/transport research index",
    "glyph/gfw2-storage-transport-research-index",
    "all implementation classes blocked remain protobuf binary generation, WebSerial transport, device write, runtime-loaded storage, runtime-loaded interpreter, and official configurator compatibility claims",
    "allowed next work stays limited to docs/tools validators, offline JSON adapter planning, manual no-device import/export experiment planning, and source audits",
    "Offline remapper adapter target contract",
    "glyph/gfw2-offline-remapper-adapter-target-contract",
    "offline adapter plan only",
    "adapter not implemented, external source not authority, not official configurator compatibility, not device write behavior, not WebSerial transport, not protobuf binary generation, not runtime-loaded config, and not hardware validation",
    "Offline remapper adapter mapping plan",
    "glyph/gfw2-offline-remapper-adapter-mapping-plan",
    "mapping plan only",
    "generated config tables not direct until custom modifier representation is source-audited",
    "custom modifier representation requires source audit",
    "protobuf binary payload mapping remains `blocked_missing_source_authority`",
    "WebSerial/device write fields remain out of scope",
    "Offline remapper adapter gap matrix",
    "glyph/gfw2-offline-remapper-adapter-gap-matrix",
    "blocked-field gap matrix",
    "no adapter generation",
    "no external code reuse",
    "no device write behavior",
    "no WebSerial transport",
    "not hardware validation",
    "Offline remapper manual experiment packet",
    "glyph/gfw2-offline-remapper-manual-experiment-packet",
    "planned_not_executed",
    "no live device",
    "no WebSerial write",
    "no Save to Device",
    "adapter not implemented",
    "not official compatibility",
    "external app URL/version/commit if available",
    "input/exported artifact hashes",
    "no source-authority promotion caveat",
    "Offline remapper experiment input manifest",
    "glyph/gfw2-offline-remapper-experiment-input-manifest",
    "input_manifest_only_experiment_not_executed",
    "input manifest only",
    "primary import candidate for external remapper no-device import test",
    "secondary repo fixture reference",
    "reference-only package, not expected external remapper import unless future adapter exists",
    "reference-only runtime candidate, not expected external remapper import unless future adapter exists",
    "reference-only generated config source",
    "adapter not implemented",
    "no device write",
    "no WebSerial write",
    "not hardware validation",
    "Offline remapper manual procedure",
    "glyph/gfw2-offline-remapper-manual-procedure",
    "procedure_only_not_executed",
    "procedure only",
    "do not click Connect",
    "do not click Save to Device",
    "do not grant WebSerial",
    "save exported JSON outside repo first",
    "compute/record exported artifact hash later in result fixture",
    "compare exported JSON only in later result-recording branch",
    "do not change repo fixtures to fit external app",
    "not official compatibility",
    "Offline remapper experiment readiness index",
    "glyph/gfw2-offline-remapper-experiment-readiness-index",
    "ready_for_manual_no_device_experiment",
    "ready for manual no-device experiment",
    "experiment not executed",
    "adapter not implemented",
    "no live device",
    "no WebSerial access",
    "no Save to Device",
    "Offline remapper experiment result",
    "glyph/gfw2-offline-remapper-experiment-result",
    "manual_no_device_experiment_completed_with_warnings",
    "manual no-device external-remapper import/export experiment",
    "profile-level import/export works",
    "not faithful to firmware-owned identity-runtime custom behavior",
    "No Glyph was connected",
    "Connect/WebSerial access was not used",
    "Save to Device was not clicked",
    "not official configurator compatibility",
    "not adapter implementation",
    "not runtime-loaded config",
    "not hardware validation",
    "Offline remapper export structural diff",
    "glyph/gfw2-offline-remapper-export-structural-diff-core",
    "docs_tools_structural_diff",
    "matching top-level keys and matching list counts",
    "byte hashes and parsed JSON objects are not equal",
    "structural diff only",
    "not firmware behavior validation",
    "not device write behavior",
    "Offline remapper Ultimate diff report",
    "glyph/gfw2-offline-remapper-ultimate-diff-report",
    "docs_tools_ultimate_profile_diff",
    "MODE_ULTIMATE profile-level diff",
    "profile-level representation only",
    "runtime-owned behavior not represented",
    "not gameplay correctness",
    "Offline remapper metadata diff report",
    "glyph/gfw2-offline-remapper-metadata-diff-report",
    "metadata diff only",
    "not gameplay/runtime validation",
    "not firmware behavior correctness",
    "not official configurator compatibility",
    "not hardware validation",
    "comparison summary",
    "Offline remapper export diff gate",
    "glyph/gfw2-offline-remapper-export-diff-gate",
    "import_export_succeeded_with_warnings_adapter_blocked",
    "import/export succeeded with warnings",
    "runtime-owned behavior not represented",
    "adapter remains blocked",
    "device write/WebSerial remains blocked",
    "protobuf binary generation remains blocked",
    "runtime-loaded config remains blocked",
    "docs/tools-only adapter candidate schema planning",
    "Offline remapper binding-loss classification",
    "glyph/gfw2-offline-remapper-binding-loss-classification",
    "docs_tools_binding_loss_classification",
    "adapter_blocking_loss",
    "external remapper export cannot currently preserve active profile artifact identity/activation binding semantics",
    "profile-level export is not round-trip safe for the active profile artifact",
    "not evidence of firmware/runtime behavior",
    "external-remapper-compatible JSON generation",
    "official compatibility claim",
    "Offline remapper SOCD drift classification",
    "glyph/gfw2-offline-remapper-socd-drift-classification",
    "docs_tools_socd_drift_classification",
    "adapter_blocking_drift",
    "external remapper export changes profile-level SOCD structure",
    "no gameplay/runtime correctness can be inferred",
    "no official compatibility claim",
    "input SOCD count = 4",
    "exported SOCD count = 6",
    "BTN_LF2/BTN_RF4",
    "BTN_LF8/BTN_LF6",
    "BTN_RF7/BTN_RF8",
    "BTN_LF5/BTN_LF2",
    "Offline remapper adapter blocker escalation",
    "glyph/gfw2-offline-remapper-adapter-blocker-escalation",
    "docs_tools_adapter_blocker_escalation",
    "Adapter implementation remains blocked",
    "External-remapper-compatible JSON generation remains blocked",
    "Active profile artifact is not round-trip safe through external remapper export",
    "Binding-loss and SOCD drift are adapter-blocking until source audit and transformation strategy exist",
    "target external remapper import only, not export round-trip",
    "use sidecar reports for runtime-owned behavior",
    "avoid using external remapper as a canonical editor for identity-runtime profiles",
    "No external source authority promotion",
    "Offline remapper export loss gate",
    "glyph/gfw2-offline-remapper-export-loss-gate",
    "external_remapper_round_trip_not_safe_adapter_blocked",
    "manual no-device import/export experiment completed",
    "binding-loss classification is adapter-blocking",
    "SOCD drift classification is adapter-blocking",
    "metadata diff report remains metadata-only evidence",
    "export diff gate keeps runtime-owned behavior unrepresented",
    "active profile round-trip is not safe",
    "external JSON generation remains blocked",
    "docs/tools-only adapter candidate schema planning with explicit non-round-trip caveat",
    "manual repeat experiment with browser/version recorded",
    "source audit of external remapper import/export code",
    "clean-room transform design, not implementation",
    "Glyph clean-room adapter candidate schema contract",
    "glyph/gfw2-clean-room-adapter-candidate-schema-contract",
    "schema_contract_only_adapter_not_implemented",
    "target: future clean-room adapter candidate schema",
    "target output is not generated",
    "target output is not round-trip safe by default",
    "active profile round-trip is currently unsafe",
    "external remapper export is not canonical",
    "official compatibility remains unclaimed",
    "no external code reuse",
    "no external dependency",
    "no device write/WebSerial/protobuf/runtime-loaded config",
    "Glyph clean-room adapter candidate schema validator",
    "glyph/gfw2-clean-room-adapter-candidate-schema-validator",
    "placeholder_only_no_adapter_output",
    "placeholder only",
    "adapter not implemented",
    "not adapter output",
    "not an external-remapper-compatible JSON candidate",
    "not round-trip safe",
    "external JSON is not generated",
    "no output path to external JSON exists",
    "no generated artifact is referenced",
    "Offline remapper result template",
    "glyph/gfw2-offline-remapper-result-template",
    "template_not_executed",
    "result template only",
    "no device connected",
    "no WebSerial access",
    "no Save to Device",
    "no device write attempted",
    "not official compatibility",
    "not hardware validation",
]


def check_exists(repo_root: Path, rel_path: str) -> bool:
    return (repo_root / rel_path).exists()


def main() -> int:
    repo_root = Path(__file__).resolve().parents[1]
    missing_required: list[str] = []
    missing_optional: list[str] = []

    print("[roadmap-check] verifying required roadmap references")
    for rel in REQUIRED_FILES:
        if check_exists(repo_root, rel):
            print(f"[roadmap-check] OK required={rel}")
        else:
            print(f"[roadmap-check] MISSING required={rel}")
            missing_required.append(rel)

    print("[roadmap-check] verifying optional future references")
    for rel in OPTIONAL_FUTURE_FILES:
        if check_exists(repo_root, rel):
            print(f"[roadmap-check] OK optional={rel}")
        else:
            print(f"[roadmap-check] WARNING optional_missing={rel}")
            missing_optional.append(rel)

    print("[roadmap-check] verifying required roadmap phrases")
    roadmap_text = (repo_root / REQUIRED_FILES[0]).read_text(encoding="utf-8")
    missing_phrases: list[str] = []
    for phrase in REQUIRED_ROADMAP_PHRASES:
        if phrase in roadmap_text:
            print(f"[roadmap-check] OK phrase={phrase}")
        else:
            print(f"[roadmap-check] MISSING phrase={phrase}")
            missing_phrases.append(phrase)

    if missing_required or missing_phrases:
        print(
            "[roadmap-check] FAIL missing_required_count="
            f"{len(missing_required)}"
        )
        if missing_phrases:
            print(
                "[roadmap-check] FAIL missing_phrase_count="
                f"{len(missing_phrases)}"
            )
        return 1

    print(
        "[roadmap-check] PASS required_count="
        f"{len(REQUIRED_FILES)} optional_missing_count={len(missing_optional)}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
